In [118]:
import pandas as pd
from sklearn.model_selection import cross_val_score

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.metrics import roc_auc_score

%matplotlib inline
import pygal
import math
import numpy as np
from IPython.display import display, HTML
base_html = """
<!DOCTYPE html>
<html>
  <head>
  <script type="text/javascript" src="http://kozea.github.com/pygal.js/javascripts/svg.jquery.js"></script>
  <script type="text/javascript" src="https://kozea.github.io/pygal.js/2.0.x/pygal-tooltips.min.js""></script>
  </head>
  <body>
    <figure>
      {rendered_chart}
    </figure>
  </body>
</html>
"""

En esta seccion desarrolle un modulo de clasificacion para predecir si el usuario ganara o perdera su partida

In [119]:
df=pd.read_csv('./csv/data.csv')

In [120]:
for i in df.columns:
    print(i)

gameId
platformId
gameCreation
gameDuration
queueId
mapId
seasonId
gameVersion
gameMode
gameType
teamId
win
firstBlood
firstTower
firstInhibitor
firstBaron
firstDragon
firstRiftHerald
towerKills
inhibitorKills
baronKills
dragonKills
vilemawKills
riftHeraldKills
dominionVictoryScore
participantId
championId
spell1Id
spell2Id
item0
item1
item2
item3
item4
item5
item6
kills
deaths
assists
largestKillingSpree
largestMultiKill
killingSprees
longestTimeSpentLiving
doubleKills
tripleKills
quadraKills
pentaKills
unrealKills
totalDamageDealt
magicDamageDealt
physicalDamageDealt
trueDamageDealt
largestCriticalStrike
totalDamageDealtToChampions
magicDamageDealtToChampions
physicalDamageDealtToChampions
trueDamageDealtToChampions
totalHeal
totalUnitsHealed
damageSelfMitigated
damageDealtToObjectives
damageDealtToTurrets
visionScore
timeCCingOthers
totalDamageTaken
magicalDamageTaken
physicalDamageTaken
trueDamageTaken
goldEarned
goldSpent
turretKills
totalMinionsKilled
neutralMinionsKilled
neutral

In [121]:
for i, j in zip(df.isna().sum().index, df.isna().sum()):
    print(i,j)

gameId 0
platformId 0
gameCreation 0
gameDuration 0
queueId 0
mapId 0
seasonId 0
gameVersion 0
gameMode 0
gameType 0
teamId 0
win 0
firstBlood 0
firstTower 0
firstInhibitor 0
firstBaron 0
firstDragon 0
firstRiftHerald 0
towerKills 0
inhibitorKills 0
baronKills 0
dragonKills 0
vilemawKills 0
riftHeraldKills 0
dominionVictoryScore 0
participantId 0
championId 0
spell1Id 0
spell2Id 0
item0 0
item1 0
item2 0
item3 0
item4 0
item5 0
item6 0
kills 0
deaths 0
assists 0
largestKillingSpree 0
largestMultiKill 0
killingSprees 0
longestTimeSpentLiving 0
doubleKills 0
tripleKills 0
quadraKills 0
pentaKills 0
unrealKills 0
totalDamageDealt 0
magicDamageDealt 0
physicalDamageDealt 0
trueDamageDealt 0
largestCriticalStrike 0
totalDamageDealtToChampions 0
magicDamageDealtToChampions 0
physicalDamageDealtToChampions 0
trueDamageDealtToChampions 0
totalHeal 0
totalUnitsHealed 0
damageSelfMitigated 0
damageDealtToObjectives 0
damageDealtToTurrets 0
visionScore 0
timeCCingOthers 0
totalDamageTaken 0
magic

In [122]:
tgt="win"
ls_pred=["kills","deaths","assists","turretKills","totalDamageDealt",
"magicDamageDealt",
"physicalDamageDealt",
"trueDamageDealt",
"wardsPlaced",
"wardsKilled",
"totalDamageTaken",
"magicalDamageTaken",
"physicalDamageTaken",
"trueDamageTaken",
"totalDamageDealt",
"magicDamageDealt",
"physicalDamageDealt",
"trueDamageDealt",
"firstBlood",
"firstTower",
"firstInhibitor",
"firstBaron",
"firstDragon",
"firstRiftHerald",
"towerKills",
"inhibitorKills",
"baronKills",
"dragonKills",
"riftHeraldKills",
"gameDuration"]

In [123]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [124]:
escalar=StandardScaler()

In [125]:
X_train, X_test, y_train, y_test = train_test_split(df[ls_pred], df[tgt], test_size=0.33, random_state=42)

In [126]:
X_train=escalar.fit_transform(X_train)
X_test=escalar.transform(X_test)|

In [127]:
reg_grid = {
    'penalty':['l1','l2','elasticnet','none'],
    'dual':[True,False],
    'class_weight':['balanced','None'],
    'solver':['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'],
    'tol':[.0001,.0002,.0003,.0004,.0005],
    'multi_class':['ovr', 'multinomial', 'auto']
}

In [128]:
regLog=LogisticRegression()
clf = GridSearchCV(regLog, reg_grid, cv=4, error_score=-1000, n_jobs=-1, scoring="accuracy")
clf.fit(X_train, y_train)
print("Best score: " + str(clf.best_score_))

Best score: 0.8660049627791563


/home/arturo/virtualenv/ml/lib/python3.7/site-packages/sklearn/linear_model/sag.py:337: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


In [129]:
clf.best_estimator_

LogisticRegression(C=1.0, class_weight='None', dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='ovr', n_jobs=None, penalty='l1',
                   random_state=None, solver='saga', tol=0.0001, verbose=0,
                   warm_start=False)

In [130]:
regLog=LogisticRegression()

In [131]:
regLog.fit(X_train,y_train)

/home/arturo/virtualenv/ml/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [132]:
regLog.predict(X_test).sum()

113

In [133]:
y_test.sum()

107

In [134]:
[(x, y) for x, y in zip(ls_pred, regLog.coef_[0])]

[('kills', 0.8593373281613672),
 ('deaths', -1.46451913628026),
 ('assists', 1.5542760374750484),
 ('turretKills', 0.5540799579859407),
 ('totalDamageDealt', 0.014571877827540703),
 ('magicDamageDealt', -0.0857283784163155),
 ('physicalDamageDealt', 0.053318043042450955),
 ('trueDamageDealt', 0.06051796650294791),
 ('wardsPlaced', -0.22816143334712682),
 ('wardsKilled', -0.22554956596432837),
 ('totalDamageTaken', -0.10675171271269127),
 ('magicalDamageTaken', -0.0002738759395426746),
 ('physicalDamageTaken', -0.00020634048817493988),
 ('trueDamageTaken', -0.5818328248418969),
 ('totalDamageDealt', 0.014571877827540703),
 ('magicDamageDealt', -0.0857283784163155),
 ('physicalDamageDealt', 0.05331804304245099),
 ('trueDamageDealt', 0.060517966502947926),
 ('firstBlood', -0.11858641265084706),
 ('firstTower', 0.2121378712602401),
 ('firstInhibitor', 0.29055253106251344),
 ('firstBaron', -0.3812729103314979),
 ('firstDragon', -0.21926106651214997),
 ('firstRiftHerald', 0.0626929626109602)

In [135]:
from sklearn.model_selection import cross_val_score

In [136]:
cross_val_score(regLog, X_train, y_train, cv=3, scoring="accuracy")

/home/arturo/virtualenv/ml/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/arturo/virtualenv/ml/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/arturo/virtualenv/ml/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([0.87407407, 0.85185185, 0.87218045])

In [137]:
from sklearn.model_selection import cross_val_predict

In [138]:
y_train_pred = cross_val_predict(regLog, X_train, y_train, cv=3)

/home/arturo/virtualenv/ml/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/arturo/virtualenv/ml/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/arturo/virtualenv/ml/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [139]:
from sklearn.metrics import confusion_matrix

In [140]:
confusion_matrix(y_train, y_train_pred)

array([[131,  27],
       [ 27, 218]])

In [142]:
 from sklearn.metrics import precision_score, recall_score

In [143]:
precision_score(y_train, y_train_pred) 

0.889795918367347

In [144]:
recall_score(y_train, y_train_pred)

0.889795918367347

In [145]:
from sklearn.metrics import f1_score

In [146]:
 f1_score(y_train, y_train_pred)

0.889795918367347

In [147]:
pd.to_pickle(regLog, "./logistic.pickle")

In [148]:
test=pd.read_pickle("./logistic.pickle")

In [149]:
pd.Series(test.predict(X_test)).value_counts()

True     113
False     86
dtype: int64

In [150]:
y_test.value_counts()

True     107
False     92
Name: win, dtype: int64

In [151]:
y_test.values

array([ True, False,  True,  True, False, False,  True, False,  True,
       False,  True,  True, False,  True, False, False, False,  True,
       False,  True,  True, False,  True,  True, False, False, False,
       False,  True,  True, False,  True, False,  True,  True,  True,
        True, False, False,  True,  True, False, False,  True,  True,
       False,  True, False,  True,  True, False,  True,  True, False,
        True, False,  True,  True,  True,  True,  True, False,  True,
       False, False,  True,  True,  True,  True, False,  True,  True,
        True, False,  True, False,  True, False, False,  True, False,
        True,  True, False, False, False,  True, False, False, False,
       False, False, False, False,  True, False,  True, False,  True,
        True,  True, False,  True,  True,  True, False, False, False,
       False,  True,  True, False,  True,  True, False,  True,  True,
        True, False, False,  True,  True, False,  True,  True,  True,
       False, False,